name: xarray-with-cubed-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiobotocore
  - array-api-strict
  - boto3
  - bottleneck
  - cartopy
  - cftime
  - flox
  - fsspec
  - h5netcdf
  - h5py
  - hdf5
  - hypothesis
  - iris
  - lxml # Optional dep of pydap
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numba
  - numbagg
  - numexpr
  - numpy>=2.2
  - opt_einsum
  - packaging
  - pandas
  - pip
  - pooch
  - pre-commit
  - pyarrow
  - pydap
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-env
  - pytest-timeout
  - pytest-xdist
  - rasterio
  - scipy
  - seaborn
  - sparse
  - toolz
  - typing_extensions
  - zarr
  - pip:
      - cubed
      - cubed-xarray
